language: node_js

sudo: required

services:
  - docker

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - webapp/node_modules

before_script:
  - cd webapp

script:
  - yarn
  - test -z "$(git diff)"
  - yarn lint
  - yarn build
  - yarn test
  - yarn shooting-stars

