import '../src/locale'

import './Button'
import './Card'
import './Colors'
import './Alert'
import './Switch'
import './Progress'
import './Tag'
import './TabBar'
import './Typography'
import './FormFields'
import './Grid'
import './ContextSwitch'
import './Filters'
import './Legend'
import './DateSelector'
import './Toolbar'
