version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - webapp-dependencies-{{ checksum "webapp/package.json" }}
          - webapp-dependencies-

      - run: |
          cd webapp
          npm install -g yarn
          yarn
          yarn lint
          yarn build
          yarn test
          yarn percy
          yarn visual-tests

      - save_cache:
          paths:
            - webapp/node_modules

          key: webapp-dependencies-{{ checksum "webapp/package.json" }}

